CREATE TABLE IF NOT EXISTS nodes (
	uuid TEXT PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	cpu_cores INTEGER NOT NULL,
	memory_mb INTEGER NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);